addons:
    js:
        - 'addon/display/fullscreen.js'
        - 'addon/display/panel.js'
        - 'addon/edit/closebrackets.js'
        - 'addon/edit/closetag.js'
        - 'addon/edit/matchbrackets.js'
        - 'addon/edit/matchtags.js'
        - 'addon/fold/brace-fold.js'
        - 'addon/fold/foldcode.js'
        - 'addon/fold/foldgutter.js'
        - 'addon/fold/xml-fold.js'
        - 'addon/mode/loadmode.js'
        - 'addon/mode/multiplex.js'
        - 'addon/scroll/annotatescrollbar.js'
        - 'addon/scroll/simplescrollbars.js'
        - 'addon/search/matchesonscrollbar.js'
        - 'addon/search/match-highlighter.js'
        - 'addon/search/searchcursor.js'
        - 'addon/selection/active-line.js'
        - 'keymap/vim.js'
    css:
        - 'addon/display/fullscreen.css'
        - 'addon/fold/foldgutter.css'
        - 'addon/search/matchesonscrollbar.css'
        - 'addon/scroll/simplescrollbars.css'
